apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: applicationmonitorings.applicationmonitoring.integreatly.org
spec:
  group: applicationmonitoring.integreatly.org
  names:
    kind: ApplicationMonitoring
    listKind: ApplicationMonitoringList
    plural: applicationmonitorings
    singular: applicationmonitoring
  scope: Namespaced
  validation:
    openAPIV3Schema:
      description: ApplicationMonitoring is the Schema for the applicationmonitorings
        API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: ApplicationMonitoringSpec defines the desired state of ApplicationMonitoring
          properties:
            additionalScrapeConfigSecretKey:
              description: AdditionalScrapeConfigSecretKey is the key under which
                additional scrape configs are stored within the secret
              type: string
            additionalScrapeConfigSecretName:
              description: AdditionalScrapeConfigSecretName is the name of the secret
                from which additional scrape configs will be passed to the prometheus
                operator
              type: string
            alertmanagerInstanceNamespaces:
              description: AlertmanagerInstanceNamespaces is a list of namespaces
                to watch for alertmanager custom resources
              type: string
            labelSelector:
              description: LabelSelector is a selector used by the Prometheus and
                Grafana Operators to discover resources
              minLength: 1
              type: string
            prometheusInstanceNamespaces:
              description: PrometheusInstanceNamespaces is a list of namespaces to
                watch for prometheus custom resources
              type: string
            prometheusRetention:
              description: PrometheusRetention specifies retention time for prometheus
                data. See https://prometheus.io/docs/prometheus/latest/storage/
              type: string
            prometheusStorageRequest:
              description: PrometheusStorageRequest is the amount of storage to assign
                to a volume claim for persisting Prometheus data. See https://github.com/coreos/prometheus-operator/blob/ca400fdc3edd0af0df896a338eca270e115b74d7/Documentation/api.md#storagespec
              type: string
            selfSignedCerts:
              description: SelfSignedCerts is a flag indicating whether self-signed
                certs are expected for routes in the blackbox target exporter in Prometheus
              type: boolean
          required:
          - labelSelector
          type: object
        status:
          description: ApplicationMonitoringStatus defines the observed state of ApplicationMonitoring
          properties:
            lastblackboxconfig:
              description: LastBlackboxConfig is an md5 hash of the Blackbox target
                config
              type: string
            phase:
              description: Phase is a number representing the installation progress
                of the monitoring components
              type: integer
          required:
          - lastblackboxconfig
          - phase
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
