#!/bin/bash -e
#
# Test the Dockerfile.tools image.
#
# IMAGE_NAME specifies the name of the candidate image used for testing.
# The image has to be available before this script is executed.
#
WORK_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

docker run --rm --entrypoint=/bin/sh ${IMAGE_NAME} -c 'operator-sdk version'
docker run --rm --entrypoint=/bin/sh ${IMAGE_NAME} -c 'go version'

docker run --rm -u $UID -v "${WORK_DIR}/../..:/application-monitoring-operator:z" --entrypoint=/bin/sh ${IMAGE_NAME} -c "cd /application-monitoring-operator && make test/unit"

echo "SUCCESS!"