apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: blackboxtargets.applicationmonitoring.integreatly.org
spec:
  group: applicationmonitoring.integreatly.org
  names:
    kind: BlackboxTarget
    listKind: BlackboxTargetList
    plural: blackboxtargets
    singular: blackboxtarget
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            blackboxTargets:
              description: 'Defines an endpoint which can be probed using the Prometheus Blackbox exporter'
              items:
                properties:
                  module:
                    type: string
                  service:
                    type: string
                  url:
                    type: string
                required:
                - url
                - service
                - module
                type: object
              type: array
          type: object
        status:
          properties:
            phase:
              description: 'The field phase is a status field indicating which phase the controller is with regards to reconciling blackbox target resources.'
              format: int64
              type: integer
          required:
          - phase
          type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
