apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-serviceaccount
  namespace: {{ .Namespace }}
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.primary: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"grafana-route"}}' 