apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: {{ .GrafanaCrName }}
  namespace: {{ .Namespace }}
spec:
  prometheusUrl: "http://prometheus-service:9090"
  monitoringNamespaceSelector:
    matchLabels:
      monitoring-key: middleware
