apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .GrafanaOperatorName }}
  namespace: {{ .Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ .GrafanaOperatorName }}
    matchLabels:
      app: "syndesis"
  template:
    metadata:
      labels:
        name: {{ .GrafanaOperatorName }}
    spec:
      serviceAccountName: grafana-operator
      containers:
        - name: {{ .GrafanaOperatorName }}
          image: {{ .GrafanaImage }}
          args:
            - '--grafana-image=registry.redhat.io/openshift3/grafana'
            - '--grafana-image-tag=v3.11'
            - '--openshift'
            - '--scan-all'
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - {{ .GrafanaOperatorName }}
          imagePullPolicy: Always
          readinessProbe:
            exec:
              command:
                - stat
                - /tmp/operator-sdk-ready
            initialDelaySeconds: 4
            periodSeconds: 10
            failureThreshold: 1
          env:
            - name: TEMPLATE_PATH
              value: /usr/local/bin/templates
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "{{ .GrafanaOperatorName }}"
